import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Language Basics',
      items: [{ type: 'autogenerated', dirName: 'language-basics' }],
    },
    {
      type: 'category',
      label: 'Control Flow',
      items: [{ type: 'autogenerated', dirName: 'control-flow' }],
    },
    {
      type: 'category',
      label: 'Functions',
      items: [{ type: 'autogenerated', dirName: 'functions' }],
    },
    {
      type: 'category',
      label: 'Async',
      items: [{ type: 'autogenerated', dirName: 'async-execution-model' }],
    },
    {
      type: 'category',
      label: 'Errors',
      items: [{ type: 'autogenerated', dirName: 'error-handling' }],
    },
    {
      type: 'category',
      label: 'Modules & Packages',
      items: [{ type: 'autogenerated', dirName: 'modules-packages' }],
    },
    {
      type: 'category',
      label: 'Standard Library',
      items: [{ type: 'autogenerated', dirName: 'standard-library' }],
    },
    {
      type: 'category',
      label: 'CLI',
      items: [{ type: 'autogenerated', dirName: 'tooling-cli' }],
    },
    {
      type: 'category',
      label: 'Runtime Internals',
      items: [{ type: 'autogenerated', dirName: 'runtime-internals' }],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [{ type: 'autogenerated', dirName: 'contribution-governance' }],
    },
  ],
};

export default sidebars;
